CLEAR MACROS
SET TALK OFF
SET EXACT ON
SET BELL OFF
SET HELP OFF
SET CLOCK OFF
SET STATUS OFF
SET ESCAPE OFF
SET SHADOWS ON
SET DELETED ON
SET SAFETY OFF
SET DATE british
SET REFRESH TO 0.5 
SET REFRESH TO 0
SET DISPLAY TO VGA25
SET CENTURY ON
SET UDFPARMS TO VALUE
SET PROCEDURE TO RUTINAS
DEACTIVATE MENU mainmenu
SET SYSMENU OFF
DO desactiva_
SET EXCLUSIVE OFF
= CAPSLOCK(.T.)
= INSMODE(.T.)
IF app
     ON KEY LABEL alt+q cancel
ENDIF
RETURN
*
